const paragraphs = [
"In today's digital age, proficient typing skills are highly valued. Being able to type quickly and accurately can significantly boost your productivity and efficiency. Whether you're writing an email, creating a document, or coding a program, mastering the art of typing will save you time and effort. Practice regularly, use proper ergonomics, and soon you'll be typing like a pro!",
"The world of technology continues to evolve at a rapid pace. In this digital era, typing has become an essential skill for communication and productivity. Whether you're a student, a professional, or simply navigating the online realm, the ability to type quickly and accurately is crucial. So, grab your keyboard, keep practicing, and soon you'll be typing with lightning speed!",
"The keyboard is your gateway to the digital world. It's where your thoughts and ideas take shape. As you embark on your typing journey, remember to focus on both speed and accuracy. Speed without accuracy leads to errors, while accuracy without speed can hinder your productivity. Strike a balance, practice consistently, and watch your typing skills soar to new heights.",
"Efficient typing is like a dance between your fingers and the keyboard. Each key represents a step in the rhythm. With practice, the steps become smoother, and the dance becomes effortless. Remember to maintain a relaxed posture, use the right finger placement, and let your fingers glide across the keys. Embrace the rhythm of typing, and you'll find yourself typing with grace and speed.",
"The ability to type quickly and accurately is an invaluable asset in today's fast-paced world. Whether you're a writer, a student, or a professional, honing your typing skills will give you a competitive edge. Practice regularly, challenge yourself with typing exercises, and track your progress. Soon enough, you'll be amazed at how effortlessly your fingers fly across the keyboard.",
"As you embark on your typing journey, remember that practice makes perfect. Set aside dedicated time each day to focus on improving your typing skills. Start with the basics, familiarize yourself with the keyboard layout, and gradually increase your speed. Don't worry about mistakes; they're part of the learning process. Stay consistent, stay patient, and watch your typing prowess grow.",
"The world of typing is filled with exciting challenges and rewarding accomplishments. From mastering touch typing to increasing your words per minute, each milestone brings a sense of achievement. So, embrace the journey, conquer the keyboard, and unlock the power of your fingertips. With determination and practice, you'll become a typing virtuoso in no time.",
"In the digital age, typing has become an essential life skill. It opens doors to countless opportunities, from efficient communication to online collaboration. So, make it a priority to develop your typing abilities. Set goals, measure your progress, and celebrate your achievements along the way. Remember, every keystroke brings you one step closer to typing mastery.",
"Efficiency is the key to success in the modern world, and typing is no exception. Enhancing your typing speed and accuracy can save you valuable time and increase your productivity. Imagine effortlessly drafting emails, writing reports, or coding complex programs with ease. Embrace the challenge, invest in your skills, and unlock the true potential of your typing prowess.",
"As you embark on your typing journey, take a moment to appreciate the power of words. Every keystroke carries the potential to create, inspire, and connect. Whether you're crafting a compelling story or composing a thoughtful message, let your fingers dance across the keyboard, giving life to your thoughts. Harness the art of typing, and let your words resonate with the world.",
"The path to typing proficiency begins with discipline and determination. Treat each typing session as an opportunity for growth and improvement. Focus on technique, strive for accuracy, and gradually increase your speed. Embrace the challenges, learn from your mistakes, and watch as your fingers effortlessly glide across the keyboard, transforming your thoughts into words.",
"Unlock the true potential of your keyboard by mastering the art of typing. With each word, sentence, and paragraph you type, you have the ability to convey ideas, share knowledge, and inspire others. So, embark on this journey with passion and purpose. Let your fingertips become the conduit through which your thoughts come to life. Embrace the power of typing, and let your words shape the world.",
"Typing is more than just a mechanical action; it's a form of self-expression. As you practice, let your personality shine through your fingertips. Find your own rhythm, develop your own style, and make the keyboard an extension of your creative spirit. With dedication and perseverance, your typing skills will become a reflection of your unique voice.",
"In the realm of digital communication, precision and speed go hand in hand. Typing proficiency enables you to convey your thoughts effectively, keeping pace with the demands of the modern world. Each keystroke is an opportunity to make an impact, whether it's a concise message, an engaging article, or a meticulously crafted code. So, refine your skills, embrace the power of typing, and make your mark.",
"As you embark on your typing journey, remember the importance of focus. In a world filled with distractions, typing requires concentration and mindfulness. Create a quiet space, clear your mind, and immerse yourself in the rhythm of the keys. With each keystroke, let the world around you fade away, and allow yourself to be fully present in the act of typing.",
"Discover the joy of typing, where letters dance beneath your fingertips and words come to life on the screen. Embrace the gentle rhythm of the keys as they respond to your touch. With each stroke, immerse yourself in the flow of thoughts and ideas, and witness the magic of how the simple act of typing can transform imagination into reality.",
"Typing is not just about pressing keys; it's about finding harmony between your thoughts and the written word. With every stroke, you have the power to shape language and create meaning. So, approach typing with intention and purpose. Let your fingers become conduits for your ideas, and let the keyboard be your canvas. Paint a masterpiece with words.",
"The journey of a thousand words begins with a single keystroke. As you embark on your typing adventure, remember that progress comes with persistence. Don't be discouraged by initial challenges; instead, view them as opportunities to learn and grow. Stay committed, stay motivated, and embrace the exciting world of typing. Your future self will thank you for it."
];

const codelines = [
  "let x=10;for(let i=0;i<5;i++){x+=i;}console.log(x);let arr=[1,2,3];for(let num of arr){console.log(num);}function greet(name){console.log(`Hello, ${name}!`);}greet('John');let sum=function(a,b){return a+b;};console.log(sum(2,3));let obj={name:'Alice',age:25};console.log(obj.name,obj.age);class Person{constructor(name){this.name=name;}greet(){console.log(`Hello, ${this.name}!`);}}",
  "const calculateSum = (a, b) => a + b; const multiplyNumbers = (a, b) => a * b; const divideNumbers = (a, b) => a / b; const subtractNumbers = (a, b) => a - b; const getSquareRoot = (num) => Math.sqrt(num); const generateRandomNumber = () => Math.random(); const convertToUpperCase = (str) => str.toUpperCase(); const checkIfArray = (arr) => Array.isArray(arr); const getLength = (arr) => arr.length;",
  "const findMaxValue = (arr) => Math.max(...arr); const findMinValue = (arr) => Math.min(...arr); const capitalizeFirstLetter = (str) => str.charAt(0).toUpperCase() + str.slice(1); const checkIfPalindrome = (str) => str === str.split('').reverse().join(''); const generateRandomInteger = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;", 
  "const calculateFactorial = (num) => { if (num === 0 || num === 1) return 1; return num * calculateFactorial(num - 1); }; const formatDate = (date) => { const options = { year: 'numeric', month: 'long', day: 'numeric' }; return date.toLocaleDateString(undefined, options); }; const reverseString = (str) => str.split('').reverse().join(''); const checkIfPrime = (num) => { if (num <= 1) return false;",
  "for (let i = 2; i <= Math.sqrt(num); i++) { if (num % i === 0) return false; } return true; }; const calculatePower = (base, exponent) => base ** exponent; const roundNumber = (num) => Math.round(num); const sortArray = (arr) => arr.sort((a, b) => a - b); const mergeArrays = (arr1, arr2) => [...arr1, ...arr2]; const getSubstring = (str, start, end) => str.substring(start, end);",
  "const removeDuplicates = (arr) => [...new Set(arr)]; const checkIfEven = (num) => num % 2 === 0; const countOccurrences = (arr, value) => arr.filter((elem) => elem === value).length; const removeWhitespace = (str) => str.replace(/g, ''); const calculateAverage = (arr) => arr.reduce((acc, curr) => acc + curr, 0) / arr.length;",
  "const sum = (a, b) => a + b;const multiply = (a, b) => a * b;const divide = (a, b) => a / b;const subtract = (a, b) => a - b;const square = (a) => a * a;const cube = (a) => a * a * a;const power = (a, b) => Math.pow(a, b);const squareRoot = (a) => Math.sqrt(a);const randomNumber = () => Math.random();const floor = (a) => Math.floor(a);const ceiling = (a) => Math.ceil(a);",
  "const absolute = (a) => Math.abs(a);const max = (a, b) => Math.max(a, b);const min = (a, b) => Math.min(a, b);const round = (a) => Math.round(a);const log = (a) => console.log(a);const alertMessage = (msg) => alert(msg);const getElement = (id) => document.getElementById(id);const createElement = (tag) => document.createElement(tag);const addClass = (element, className) => element.classList.add(className);",
  "const removeClass = (element, className) => element.classList.remove(className);const toggleClass = (element, className) => element.classList.toggle(className);const setAttribute = (element, attribute, value) => element.setAttribute(attribute, value);const removeAttribute = (element, attribute) => element.removeAttribute(attribute);const addEventListener = (element, event, callback) => element.addEventListener(event, callback);"
]
